AllCops:
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 100
  Enabled: true

Layout/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
